# examples of command line use
# rosparam load ./stretch_marker_dict.yaml
# rosparam list
# rosparam get /aruco_markers/

# Be careful with length_mm values. Stickers and printouts can vary
# significantly from your expectations. You should measure them
# directly. For example, in a prototype robot the stickers were closer
# to 23mm wide than 24mm. This 1mm difference resulted in > 1cm of
# error in the depths for the marker pose estimates when only using
# RGB images.

"aruco_marker_info":
  "0":
    "length_mm": 100
    "use_rgb_only": False
    "name": "target_tool"
    "link": "base_link"
  "80":
    "length_mm": 35
    "use_rgb_only": False
    "name": "target_0"
    "link": "base_link"
  "81":
    "length_mm": 35
    "use_rgb_only": False
    "name": "target_1"
    "link": "base_link"
  "82":
    "length_mm": 35
    "use_rgb_only": False
    "name": "target_2"
    "link": "base_link"
  "83":
    "length_mm": 35
    "use_rgb_only": False
    "name": "target_3"
    "link": "base_link"
  "84":
    "length_mm": 35
    "use_rgb_only": False
    "name": "target_4"
    "link": "base_link"
  "85":
    "length_mm": 35
    "use_rgb_only": False
    "name": "target_5"
    "link": "base_link"
