# base_local_planner: "dwa_local_planner/DWAPlannerROS"
base_local_planner: "teb_local_planner/TebLocalPlannerROS"

TebLocalPlannerROS:
  acc_lim_x: 0.4
  acc_lim_theta: 0.4
  max_vel_x: 0.6
  max_vel_x_backwards: 0.2
  max_vel_theta: 0.6
  # wheelbase: 0.3
  footprint_model:
    type: "polygon"
    vertices: [[0.05,0.175],[-0.30,0.175],[-0.30,-0.175],[0.05,-0.175]]
  
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1

  min_obstacle_dist: 0.05
  inflation_dist: 0.05
  include_dynamic_obstacles: true
  dynamic_obstacle_inflation_dist: 0.05
  costmap_obstacles_behind_robot_dist: 0.35


  odom_topic: "odom"
  map_frame: "map"


DWAPlannerROS:
  #vel params
  max_vel_x: 0.6 #safe speed for fetch to travel at
  min_vel_x: -0.1
  max_vel_trans: 0.6
  min_vel_trans: 0.1
  max_vel_y: 0  #diff drive
  min_vel_y: 0
  max_vel_theta: 1.5
  min_vel_theta: 0.4

  #accel params
  acc_lim_x: 0.7
  acc_lim_y: 0  #diff drive
  acc_lim_trans: 0.7
  acc_lim_theta: 4

  #forward sim params
  sim_time: 1.7
  vx_samples: 10
  vy_samples: 0 #diff drive
  vth_samples: 20

  #scoring params
  path_distance_bias: 32
  goal_distance_bias: 24
  occdist_scale: 1.4
  forward_point_distance: 0.3

  #higher goal tolerance
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  #lower goal tolerance
  #yaw_goal_tolerance: 0.05
  #xy_goal_tolerance: 0.1
  #latch_xy_goal_tolerance: false

  prune_plan: true
