
conservative_reset_dist: 3.0
controller_frequency: 7.0 # 7
planner_patience: 5.0 # 10.0
max_planning_retries: 10
planner_frequency: 0.01

recovery_behavior_enabled: true
recovery_behaviors:
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'

aggressive_reset:
  reset_distance: 5.0
  layer_names: ["rgbd_obstacle_layer"]

rotate_recovery:
  frequency: 5.0